-- kpmp_dvc_integration.biopsy_tracking definition

CREATE TABLE `biopsy_tracking` (
                                   `redcap_record_id` varchar(100) DEFAULT NULL,
                                   `Whole Slide Images` text DEFAULT NULL,
                                   `Single-nucleus RNA-Seq Status` text DEFAULT NULL,
                                   `Single-nucleus RNA-Seq Specimen ID` text DEFAULT NULL,
                                   `ATAC RNA-seq Status` text DEFAULT NULL,
                                   `ATAC RNA-seq Specimen ID` text DEFAULT NULL,
                                   `Single-cell RNA-Seq Status` text DEFAULT NULL,
                                   `Single-cell RNA-Seq Specimen ID` text DEFAULT NULL,
                                   `Regional Transcriptomics Status` text DEFAULT NULL,
                                   `Regional Transcriptomics Specimen ID` text DEFAULT NULL,
                                   `Bulk total/mRNA Experiment Status` text DEFAULT NULL,
                                   `Bulk total/mRNA Experiment Specimen ID` text DEFAULT NULL,
                                   `3D Tissue Imaging and Cytometry Experiment Status` text DEFAULT NULL,
                                   `3D Tissue Imaging and Cytometry Experiment Specimen ID` text DEFAULT NULL,
                                   `Regional Proteomics Experiment Status` text DEFAULT NULL,
                                   `Regional Proteomics Specimen ID` text DEFAULT NULL,
                                   `Spatial Metabolomics Experiment Status` text DEFAULT NULL,
                                   `Spatial Metabolomics Specimen ID` text DEFAULT NULL,
                                   `Spatial Lipidomics Experiment Status` text DEFAULT NULL,
                                   `Spatial Lipidomics Specimen ID` text DEFAULT NULL,
                                   `Spatial N-glycomics Experiment Status` text DEFAULT NULL,
                                   `Spatial N-glycomics Specimen ID` text DEFAULT NULL,
                                   `Spatial Transcriptomics Experiment Status` text DEFAULT NULL,
                                   `Spatial Transcriptomics Specimen ID` text DEFAULT NULL,
                                   `CODEX (IU) Experiment Status` text DEFAULT NULL,
                                   `CODEX (IU) Specimen ID` text DEFAULT NULL,
                                   `CODEX (UCSF) Experiment Status` text DEFAULT NULL,
                                   `CODEX (UCSF) Specimen ID` text DEFAULT NULL,
                                   `IMC Experiment Status` text DEFAULT NULL,
                                   `IMC Specimen ID` text DEFAULT NULL,
                                   `DNA Methyl-seq Experiment Status` text DEFAULT NULL,
                                   `DNA Methyl-seq Specimen ID` text DEFAULT NULL,
                                   `CUT & RUN Experiment Status` text DEFAULT NULL,
                                   `CUT & RUN Specimen ID` text DEFAULT NULL,
                                   `Metabolon Timed Urine - UHPLC MS-MS Experiment Status` text DEFAULT NULL,
                                   `Metabolon Timed Urine - UHPLC MS-MS Specimen ID` text DEFAULT NULL,
                                   `Metabolon Plasma EDTA - UHPLC MS-MS Experiment Status` text DEFAULT NULL,
                                   `Metabolon Plasma EDTA - UHPLC MS-MS Specimen ID` text DEFAULT NULL,
                                   `MSDQ120 Spot Urine Biomarker Specimen ID` varchar(100) DEFAULT NULL,
                                   `MSDQ120 Plasma EDTA Biomarker Status` varchar(100) DEFAULT NULL,
                                   `MSDQ120 Plasma EDTA Biomarker Specimen ID` varchar(100) DEFAULT NULL,
                                   `MSDQ120 Spot Urine Biomarker Status` varchar(100) DEFAULT NULL,
                                   `Litholink Timed Urine - BCAU680 - Status` varchar(100) DEFAULT NULL,
                                   `Litholink Timed Urine - BCAU680 - Specimen ID` varchar(100) DEFAULT NULL,
                                   `Stool Microbiome - Qaigen NextEra Status` varchar(100) DEFAULT NULL,
                                   `Stool Microbiome - Qaigen NextEra Specimen ID` varchar(100) DEFAULT NULL,
                                   `Clinical Chemistry Spot/Timed Urine - BCAU5812 Status` varchar(100) DEFAULT NULL,
                                   `Clinical Chemistry Spot/Timed Urine - BCAU5812 Specimen ID` varchar(100) DEFAULT NULL,
                                   `Clinical Chemistry Serum - BCAU5812 Status` varchar(100) DEFAULT NULL,
                                   `Clinical Chemistry Serum - BCAU5812 Specimen ID` varchar(100) DEFAULT NULL,
                                   `SomaScan Plasma EDTA - Status` varchar(100) DEFAULT NULL,
                                   `SomaScan Plasma EDTA - Specimen ID` varchar(100) DEFAULT NULL,
                                   `SomaScan Spot Urine - Status` varchar(100) DEFAULT NULL,
                                   `SomaScan Spot Urine - Specimen ID` varchar(100) DEFAULT NULL,
                                   `Descriptor Scoring (TIV)` varchar(100) DEFAULT NULL,
                                   `Segmentation/Features Data - Status` varchar(100) DEFAULT NULL,
                                   `fMRI - Status` varchar(100) DEFAULT NULL,
                                   `Retinal - Status` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;